steps:
  - label: "Maven Build using pipeline.yml"
    command: mvn clean install
    agents:
      queue: "windows"
    artifact_paths:
      - "target/*.jar"
notify:
  - email: "asthagangwar3@gmail.com"
    if: build.state == "passed"
